/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as HydrationIndexRouteImport } from './routes/hydration/index'
import { Route as BakeHistoryIndexRouteImport } from './routes/bake-history/index'
import { Route as BakeALongIndexRouteImport } from './routes/bake-a-long/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrationIndexRoute = HydrationIndexRouteImport.update({
  id: '/hydration/',
  path: '/hydration/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeHistoryIndexRoute = BakeHistoryIndexRouteImport.update({
  id: '/bake-history/',
  path: '/bake-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeALongIndexRoute = BakeALongIndexRouteImport.update({
  id: '/bake-a-long/',
  path: '/bake-a-long/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bake-a-long': typeof BakeALongIndexRoute
  '/bake-history': typeof BakeHistoryIndexRoute
  '/hydration': typeof HydrationIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bake-a-long': typeof BakeALongIndexRoute
  '/bake-history': typeof BakeHistoryIndexRoute
  '/hydration': typeof HydrationIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bake-a-long/': typeof BakeALongIndexRoute
  '/bake-history/': typeof BakeHistoryIndexRoute
  '/hydration/': typeof HydrationIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bake-a-long' | '/bake-history' | '/hydration' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bake-a-long' | '/bake-history' | '/hydration' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/bake-a-long/'
    | '/bake-history/'
    | '/hydration/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakeALongIndexRoute: typeof BakeALongIndexRoute
  BakeHistoryIndexRoute: typeof BakeHistoryIndexRoute
  HydrationIndexRoute: typeof HydrationIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydration/': {
      id: '/hydration/'
      path: '/hydration'
      fullPath: '/hydration'
      preLoaderRoute: typeof HydrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bake-history/': {
      id: '/bake-history/'
      path: '/bake-history'
      fullPath: '/bake-history'
      preLoaderRoute: typeof BakeHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bake-a-long/': {
      id: '/bake-a-long/'
      path: '/bake-a-long'
      fullPath: '/bake-a-long'
      preLoaderRoute: typeof BakeALongIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakeALongIndexRoute: BakeALongIndexRoute,
  BakeHistoryIndexRoute: BakeHistoryIndexRoute,
  HydrationIndexRoute: HydrationIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
